name: tacm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pytorch=2.4
  - pytorch-cuda=12.4
  - lightning=2.3
  - torchmetrics
  
  # Scientific computing
  - numpy>=1.21
  - scipy>=1.7
  - pandas>=1.3
  - h5py>=3.6
  
  # Visualization
  - matplotlib>=3.5
  - seaborn
  
  # Development tools
  - jupyterlab
  - notebook
  - ipywidgets
  - pytest
  - tensorboard
  
  # Machine learning utilities
  - scikit-learn
  - tqdm
  
  # Package management
  - pip
